### ISSUE TITLE
AWS HASSL URLs give 403 error

### ISSUE THREAD

**Issue by amanjeev** [DCGenomics/rnaseq_mapping_hackathon_v002#8]
https://s3.amazonaws.com/genomicdata/HASSL/* (used for the initial command to gather the reference files etc.) gives 403. Should I be accessing them from within the NCBI network?

```
Error in job get_refflat while creating output file /my/dir/GRCh38.77.compatible.ucsc.picard.refflat.txt.
403 Forbidden
2015-10-25 19:49:12 ERROR 403: Forbidden.

Error in job get_splicesites while creating output file /my/dir/Ensembl.GRCh38.77.splicesites.txt.
Error in job get_gtf while creating output file /my/dir/Homo_sapiens.GRCh38.81.gtf.gz.
RuleException:
CalledProcessError in line 189 of /home/aj/projects/ncbi/hassl/hassl.py:
Command 'wget -P /my/dir https://s3.amazonaws.com/genomicdata/HASSL/GRCh38.77.compatible.ucsc.picard.refflat.txt' returned non-zero exit status 8
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
RuleException:
CalledProcessError in line 172 of /home/aj/projects/ncbi/hassl/hassl.py:
Command 'wget -P /my/dir https://s3.amazonaws.com/genomicdata/HASSL/Ensembl.GRCh38.77.splicesites.txt' returned non-zero exit status 8
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
RuleException:
CalledProcessError in line 183 of /home/aj/projects/ncbi/hassl/hassl.py:
Command 'wget -P /my/dir https://s3.amazonaws.com/genomicdata/HASSL/Homo_sapiens.GRCh38.81.gtf.gz' returned non-zero exit status 8
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
```

**Comment by nyetsche** [comment]
I'm not familiar with that S3 bucket. It's not owned by NCBI and therefore I don't think it'd be restricted to the NCBI network.

**Comment by amanjeev** [comment]
@nyetsche Thanks! Maybe someone else can shine light on this. I will wait for someone in the contributors list to comment. cc/ @DCGenomics.

**Comment by amanjeev** [comment]
@DCGenomics I cannot assign this to anyone so just pinging here as a gentle reminder. :-)

**Comment by pcantalupo** [comment]
Hi @amanjeev 
Russ set up the S3 bucket. I was waiting to see if he would respond. Hopefully he will soon.

**Comment by nyetsche** [comment]
@amanjeev , I added you as a collaborator to the repo. So you can at least assign the ticket now :)

**Comment by amanjeev** [comment]
@pcantalupo, @nyetsche thanks! :-) I just assigned it to @russelldurrett (haha)

**Comment by amanjeev** [comment]
@russelldurrett Still no update on the S3 buckets?

**Comment by russelldurrett** [comment]
Hey @amanjeev, so sorry for the delayed response! For some reason I got (or noticed, perhaps...) the first email concerning this issue today.Glad you pinged me again! 

The bucket genomicdata is under my aws account and is fairly huge, so it has a bucket policy that moves all items to glacier if they haven't been touched in a few weeks. I've started restoring all data in s3://genomicdata/hassl/*, so if you run it again at least four hours from now you should (hypothetically) be good to go. 

Once online, I will also transition all hassl-related data to an aptly-named s3://hassl bucket and ensure the bucket policy keeps all files retrieved by the hassl.py snakemake file available off the cuff.

**Comment by russelldurrett** [comment]
actually @amanjeev that took a lot less time than expected, so if you pull the repo now it will direct your downloads to s3://hassl and all should be gravy.

**Comment by amanjeev** [comment]
@russelldurrett Thanks so much! I am sorry to bother you. It seems like some downloads are running so I guess it should be OK. 

Although I am running on my home server (just to test). Will test later when I finally get access to grid or something. cc/ @DCGenomics
